# Generated by Django 3.1.2 on 2020-10-12 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201011_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('link_type', models.CharField(choices=[('t', 'Tutorial'), ('d', 'Documentation'), ('a', 'Support Article')], default='t', max_length=1)),
                ('tags', models.CharField(max_length=150)),
                ('created_date', models.DateField(verbose_name='Created on')),
                ('planned_date', models.DateField(verbose_name='Planned for')),
                ('viewed_date', models.DateField(verbose_name='Viewed on')),
                ('github_project', models.CharField(max_length=255)),
                ('code_snippet', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('n', 'New'), ('f', 'Favorite'), ('v', 'Viewed')], default='n', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
