# Generated by Django 3.1.2 on 2020-10-13 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201013_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='link',
            name='viewed_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Viewed on'),
        ),
    ]
