# Generated by Django 3.1.2 on 2020-10-14 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201013_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=500)),
                ('note_type', models.CharField(choices=[('p', 'Possitive'), ('n', 'Negative'), ('q', 'Question')], default='p', max_length=1)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
